name: sacred_hearts
description: "Vimala_SH"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  open_file: ^3.3.2
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  http: ^1.2.1
  fluttertoast: ^8.2.4
  flutter_custom_tabs: ^2.0.0+1
  shared_preferences: ^2.2.2
  font_awesome_flutter: ^10.7.0
  flutter_native_splash: ^2.4.0
  cached_network_image: ^3.3.1
  pdf: ^3.10.8
  path_provider: ^2.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "images/logo.png"


  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
